### ISSUE TITLE
Regform comments

### ISSUE THREAD

**Issue by montanohanz** [gcfyouthlive/camplive#2]

**Comment by joshuagad** [comment]
suggestions of items that can be removed from online form:
- [x] middle initial
- [x] strand/course
- [x] parent's details section

suggestions for info to add:
- [ ] shirt measurements
- [x] how they heard about camp (if first time)

suggestions for changes:
- [x] alignment of fields
- [x] remove "Youth service" under services attended

**Comment by montanohanz** [comment]
@joshuagad noted. Tagging @jcokingli for api changes corresponding to suggestions

**Comment by joshuagad** [comment]
Another comment from yst: 
Should we also include a part for "Requests"? Esp for first timers who might want to be roomed with the person they were invited by?

**Comment by joshuagad** [comment]
Also, it's QR code, not OR code in the instructions. :)

**Comment by montanohanz** [comment]
@joshuagad i agree on the requests part but what exactly will the question on the form be?? Noted in OR QR mixup :))

**Comment by montanohanz** [comment]
re: YST Comments, Maybe we should ask for 1 contact person lang in place of the parent's details? like, name and contact lang in case of emergency. As for shirt measurements, what measurements are we talking about specifically?

**Comment by montanohanz** [comment]
@jcokingli, added a new input field with an id of first_time_hear for the question "Where did you hear about camp?". also removed parent's fields and middle initial & strand/course fields as per YST suggestions. Do your magic on the api nalang accordingly hehe :))

**Comment by montanohanz** [comment]
Current changes: Commit https://github.com/gcfyouthlive/camplive/commit/28567665211f16f8e0f6f77d21ccea100fb0c66c

**Comment by joshuagad** [comment]
Yes, please add a guardian section since there are some kids who aren’t paid for by their parents but are sponsored by others. :)

**Comment by joshuagad** [comment]
CampLIVE logo on top should be a bit bigger. But keep the size of the navbar.

**Comment by montanohanz** [comment]
Added "emergency contact section" 
Commit https://github.com/gcfyouthlive/camplive/commit/d0f9d8886c2213126cf58f5129e740859ed62727

**Comment by montanohanz** [comment]
CampLIVE Logo adjusted
Commit https://github.com/gcfyouthlive/camplive/commit/e8b83b0243cf469a7646ad77b2f2249945b2e87e

**Comment by joshuagad** [comment]
All good so far. Will pull to dev and present to YST. Will close this issue. Thanks hanz!
