### ISSUE TITLE
Keep camplive logo and navbar at fixed widths and heights

### ISSUE THREAD

**Issue by joshuagad** [gcfyouthlive/camplive#5]
Current logo has width=30%. Can you keep this at a fixed pixel width or height instead? Raising the width will also raise the height of the logo and this will force the navbar to grow in height as well.

Navbar can be at most 50-60px, whichever looks better.

**Comment by montanohanz** [comment]
Changes done :)
Commit: https://github.com/gcfyouthlive/camplive/commit/00f53e1ec2577cc6799c2f9f82494cd44f114964
